package com.botmaker.studio.project;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * The bot's runtime tuning — everything the SDK's {@code ClickConfig} exposes, plus the Linux input backend —
 * as a value, together with the generator/parser for the {@code BotSettings.java} the Studio writes into each
 * project.
 *
 * <p><b>Why a generated file rather than a settings key.</b> These knobs change what the bot <em>does</em>, not
 * how the editor looks, so they have to apply when the bot is run outside the Studio — from the command line,
 * from a published jar, from someone else's checkout. Putting them in the bot's own source is the only form
 * that travels with the code, and it keeps them readable: the user can see (and edit) exactly the calls the
 * dialog is making. The generated class has one method, {@code apply()}, called as the first statement of
 * {@code main}.
 *
 * <p>Writing regenerates the whole file from {@link #source}; reading is per-statement regex, so a file the
 * user has reformatted, commented or reordered still round-trips its values. A setting whose statement is
 * missing reads back as its default rather than failing — that is what makes hand-editing safe, and what lets
 * this parse a file generated by an older Studio that had fewer settings.
 */
public record BotSettings(boolean realInput,
                          int foundDelay,
                          int notFoundDelay,
                          double confidence,
                          boolean randomizeClicks,
                          double compareMargin,
                          int maxRetryAttempts,
                          LinuxInput linuxInput,
                          boolean isolatedSession,
                          SessionBackend sessionBackend) {

    /** The generated file's name; it sits beside the entry point in the project's own package. */
    public static final String FILE_NAME = "BotSettings.java";

    /**
     * Which Linux backend delivers real input, mirroring {@code LinuxController.selectBackend}'s
     * {@code botmaker.linux.input} property. {@link #AUTO} is the SDK's own choice and writes no property at
     * all — the others exist because "it works on my machine" here means a udev rule, an ACL or an installed
     * {@code xdotool}, and pinning the one that works on <em>this</em> machine is a per-project answer.
     */
    public enum LinuxInput {
        AUTO("auto", "Automatic (uinput, then xdotool, then XTest)"),
        UINPUT("uinput", "uinput — a virtual device the kernel reports as real"),
        XDOTOOL("xdotool", "xdotool — the XTEST extension via the xdotool command"),
        XTEST("xtest", "XTest — X11's own synthetic input");

        private final String id;
        private final String label;

        LinuxInput(String id, String label) {
            this.id = id;
            this.label = label;
        }

        /** The value written as {@code botmaker.linux.input}; stable, it lands in generated source. */
        public String id() {
            return id;
        }

        public String label() {
            return label;
        }

        /** Total parse: an unrecognised id (a newer Studio's, a typo in a hand-edit) reads back as {@link #AUTO}. */
        public static LinuxInput fromId(String id) {
            if (id == null) return AUTO;
            for (LinuxInput v : values()) {
                if (v.id.equalsIgnoreCase(id.trim())) return v;
            }
            return AUTO;
        }
    }

    /**
     * Which nested display hosts an isolated bot, mirroring the SDK's {@code Session.useBackend} and the
     * project's {@code session.backend} key. {@link #AUTO} is the SDK's own kind-driven choice — a game gets
     * gamescope (a real GPU in the private display), a plain command the lighter Xephyr — and, like
     * {@link LinuxInput#AUTO}, it writes no statement at all.
     *
     * <p>The ids are shared's {@code NestedSession.Backend.id()} values; they are persisted, so they must stay
     * stable. Pinning {@link #XEPHYR} for a game is the one combination worth avoiding: its software GL is what
     * makes store launchers and Proton titles abort.
     */
    public enum SessionBackend {
        AUTO("auto", "Automatic (gamescope for games, Xephyr for commands)"),
        GAMESCOPE("gamescope", "gamescope — a real GPU in the private display (3D games)"),
        XEPHYR("xephyr", "Xephyr — software-rendered 2D (crashes 3D games)");

        private final String id;
        private final String label;

        SessionBackend(String id, String label) {
            this.id = id;
            this.label = label;
        }

        /** The value written to {@code session.backend} and into generated source; stable. */
        public String id() {
            return id;
        }

        public String label() {
            return label;
        }

        /** Total parse: an unrecognised id (a newer Studio's, a typo in a hand-edit) reads back as {@link #AUTO}. */
        public static SessionBackend fromId(String id) {
            if (id == null) return AUTO;
            for (SessionBackend v : values()) {
                if (v.id.equalsIgnoreCase(id.trim())) return v;
            }
            return AUTO;
        }
    }

    /**
     * The SDK's own defaults ({@code ClickConfig}'s field initialisers), with real input off — and isolation
     * <b>on</b>, matching the SDK's default-on {@code Session}, so a default project generates no session
     * statement at all.
     */
    public static final BotSettings DEFAULTS =
            new BotSettings(false, 500, 200, 0.8, true, 0.05, 20, LinuxInput.AUTO, true, SessionBackend.AUTO);

    /**
     * What a Game-bot project starts with: {@link #DEFAULTS} but driving the real mouse and keyboard, because
     * a game ignores the quiet background events the SDK sends otherwise.
     */
    public static final BotSettings GAME_DEFAULTS = DEFAULTS.withRealInput(true);

    public BotSettings withRealInput(boolean enabled) {
        return new BotSettings(enabled, foundDelay, notFoundDelay, confidence, randomizeClicks, compareMargin,
                maxRetryAttempts, linuxInput, isolatedSession, sessionBackend);
    }

    /** This settings value with the session (private-display) part replaced — the dialog's save path. */
    public BotSettings withSession(boolean isolated, SessionBackend backend) {
        return new BotSettings(realInput, foundDelay, notFoundDelay, confidence, randomizeClicks, compareMargin,
                maxRetryAttempts, linuxInput, isolated, backend == null ? SessionBackend.AUTO : backend);
    }

    /** {@code BotSettings.java} for a project whose entry point is {@code mainSourceFile}. */
    public static Path fileFor(Path mainSourceFile) {
        Path dir = mainSourceFile == null ? null : mainSourceFile.getParent();
        return dir == null ? null : dir.resolve(FILE_NAME);
    }

    // --- generation ---

    /** The generated {@code BotSettings.java} source for {@code packageName} carrying these values. */
    public static String source(String packageName, BotSettings s) {
        return String.format("""
            package com.%s;

            %simport com.botmaker.sdk.api.vision.ClickConfig;

            /**
             * How this bot behaves at runtime: how long it waits after a match, how sure it has to be, and
             * whether it drives the real mouse and keyboard. GENERATED by BotMaker Studio — edit it there
             * (toolbar &rarr; Input &amp; Clicks), or by hand; the Studio reads these statements back.
             *
             * <p>It lives in your project rather than in the Studio's settings because it has to apply when the
             * bot runs <em>without</em> the Studio — from the command line, or on someone else's machine.
             */
            public final class BotSettings {

                /** Applies every setting below. Called as the first statement of the bot's main. */
                public static void apply() {
            %s%s        ClickConfig.useRealInput(%s);
                    ClickConfig.setFoundDelay(%d);
                    ClickConfig.setNotFoundDelay(%d);
                    ClickConfig.setDefaultConfidence(%s);
                    ClickConfig.enableRandomClicks(%s);
                    ClickConfig.DEFAULT_COMPARE_MARGIN = %s;
                    ClickConfig.setMaxRetryAttempts(%d);
                }

                private BotSettings() {}
            }
            """, packageName, sessionImport(s), linuxInputStatement(s), sessionStatements(s), s.realInput(),
                s.foundDelay(), s.notFoundDelay(), s.confidence(), s.randomizeClicks(), s.compareMargin(),
                s.maxRetryAttempts());
    }

    /**
     * The session lines, emitted only where they differ from the SDK's defaults — isolation is on and the
     * backend auto-selected, so a default project's generated file mentions {@code Session} nowhere. That is the
     * same rule {@link #linuxInputStatement} follows, and it is what keeps regenerating an existing default
     * project byte-identical.
     *
     * <p>They lead the method (after the Linux backend property) because the session is brought up by the first
     * {@code Target.start()}, and a call made after that point changes nothing.
     */
    private static String sessionStatements(BotSettings s) {
        StringBuilder out = new StringBuilder();
        if (!s.isolatedSession()) {
            out.append("        Session.disable();\n");
        }
        if (s.sessionBackend() != SessionBackend.AUTO) {
            out.append("        Session.useBackend(\"").append(s.sessionBackend().id()).append("\");\n");
        }
        return out.toString();
    }

    /** {@code Session}'s import, only when a session statement is emitted — an unused import is a warning. */
    private static String sessionImport(BotSettings s) {
        return sessionStatements(s).isEmpty() ? "" : "import com.botmaker.sdk.api.Session;\n";
    }

    /**
     * The Linux backend line, emitted only when it isn't {@link LinuxInput#AUTO}: automatic <em>is</em> the
     * SDK's behaviour with no property set, so writing {@code "auto"} would add a statement that says nothing —
     * and it must be set before the first {@code useRealInput} call, which is why it leads the method.
     */
    private static String linuxInputStatement(BotSettings s) {
        return s.linuxInput() == LinuxInput.AUTO ? ""
                : "        System.setProperty(\"botmaker.linux.input\", \"" + s.linuxInput().id() + "\");\n";
    }

    // --- reading ---

    private static Pattern call(String method, String valueGroup) {
        return Pattern.compile("ClickConfig\\s*\\.\\s*" + method + "\\s*\\(\\s*(" + valueGroup + ")\\s*\\)");
    }

    private static final String NUMBER = "-?\\d+(?:\\.\\d+)?";
    private static final Pattern REAL_INPUT = call("useRealInput", "true|false");
    private static final Pattern FOUND_DELAY = call("setFoundDelay", NUMBER);
    private static final Pattern NOT_FOUND_DELAY = call("setNotFoundDelay", NUMBER);
    private static final Pattern CONFIDENCE = call("setDefaultConfidence", NUMBER);
    private static final Pattern RANDOM_CLICKS = call("enableRandomClicks", "true|false");
    private static final Pattern MAX_RETRIES = call("setMaxRetryAttempts", NUMBER);
    private static final Pattern COMPARE_MARGIN = Pattern.compile(
            "ClickConfig\\s*\\.\\s*DEFAULT_COMPARE_MARGIN\\s*=\\s*(" + NUMBER + ")");
    private static final Pattern LINUX_INPUT = Pattern.compile(
            "setProperty\\s*\\(\\s*\"botmaker\\.linux\\.input\"\\s*,\\s*\"([^\"]*)\"\\s*\\)");
    /**
     * The isolation statement in any of the three spellings the facade offers — {@code Session.disable()},
     * {@code Session.enable()} and {@code Session.set(<bool>)} — because a user hand-editing this file will
     * reach for whichever reads best, and all three are real API. The captured group is normalised in
     * {@link #isolatedFrom}.
     */
    private static final Pattern SESSION_ISOLATED = Pattern.compile(
            "Session\\s*\\.\\s*(?:(enable|disable)\\s*\\(\\s*\\)|set\\s*\\(\\s*(true|false)\\s*\\))");
    private static final Pattern SESSION_BACKEND = Pattern.compile(
            "Session\\s*\\.\\s*useBackend\\s*\\(\\s*\"([^\"]*)\"\\s*\\)");

    /**
     * The settings currently written in {@code settingsFile}, falling back to {@link #DEFAULTS} for anything
     * absent (including a file that doesn't exist or can't be read) — see the class javadoc for why a missing
     * statement is a default rather than an error.
     */
    public static BotSettings read(Path settingsFile) {
        String source = "";
        if (settingsFile != null && Files.exists(settingsFile)) {
            try {
                source = Files.readString(settingsFile);
            } catch (IOException e) {
                source = "";
            }
        }
        return new BotSettings(
                bool(REAL_INPUT, source, DEFAULTS.realInput()),
                integer(FOUND_DELAY, source, DEFAULTS.foundDelay()),
                integer(NOT_FOUND_DELAY, source, DEFAULTS.notFoundDelay()),
                real(CONFIDENCE, source, DEFAULTS.confidence()),
                bool(RANDOM_CLICKS, source, DEFAULTS.randomizeClicks()),
                real(COMPARE_MARGIN, source, DEFAULTS.compareMargin()),
                integer(MAX_RETRIES, source, DEFAULTS.maxRetryAttempts()),
                LinuxInput.fromId(text(LINUX_INPUT, source)),
                isolatedFrom(source),
                SessionBackend.fromId(text(SESSION_BACKEND, source)));
    }

    /**
     * Whether {@code source} asks for isolation: absent → the default (on), which is also how a file generated
     * by an older Studio that had no session settings reads back.
     */
    private static boolean isolatedFrom(String source) {
        Matcher m = SESSION_ISOLATED.matcher(source);
        if (!m.find()) {
            return DEFAULTS.isolatedSession();
        }
        String named = m.group(1);
        return named != null ? "enable".equals(named) : Boolean.parseBoolean(m.group(2));
    }

    private static String text(Pattern p, String source) {
        Matcher m = p.matcher(source);
        return m.find() ? m.group(1) : null;
    }

    private static boolean bool(Pattern p, String source, boolean fallback) {
        String v = text(p, source);
        return v == null ? fallback : Boolean.parseBoolean(v);
    }

    private static int integer(Pattern p, String source, int fallback) {
        String v = text(p, source);
        try {
            return v == null ? fallback : (int) Math.round(Double.parseDouble(v));
        } catch (NumberFormatException e) {
            return fallback;
        }
    }

    private static double real(Pattern p, String source, double fallback) {
        String v = text(p, source);
        try {
            return v == null ? fallback : Double.parseDouble(v);
        } catch (NumberFormatException e) {
            return fallback;
        }
    }

    // --- writing ---

    /** Regenerates {@code BotSettings.java} beside the entry point, creating it if it isn't there yet. */
    public static void write(Path mainSourceFile, String packageName, BotSettings settings) throws IOException {
        Path file = fileFor(mainSourceFile);
        if (file == null) throw new IOException("No package directory for " + mainSourceFile);
        Files.createDirectories(file.getParent());
        Files.writeString(file, source(packageName, settings));
    }

    // --- migration from the old inline ClickConfig.useRealInput(…) call ---

    /** The inline call generated before {@code BotSettings.java} existed, including its trailing semicolon. */
    private static final Pattern INLINE_REAL_INPUT = Pattern.compile(
            "[ \\t]*(?:com\\.botmaker\\.sdk\\.api\\.vision\\.)?ClickConfig\\s*\\.\\s*useRealInput\\s*\\(\\s*"
                    + "(?:true|false)\\s*\\)\\s*;[ \\t]*\\r?\\n?");

    private static final Pattern MAIN_METHOD = Pattern.compile("static\\s+void\\s+main\\s*\\([^)]*\\)\\s*\\{");

    /**
     * Brings a project created before this file existed up to date: generates {@code BotSettings.java} seeded
     * from whatever its {@code main} currently says about real input, then replaces that inline call with
     * {@code BotSettings.apply();}.
     *
     * <p>Runs on project open and is a no-op once the file is there, so it costs one {@code exists} check per
     * open. It deliberately does <em>not</em> repair a project whose {@code BotSettings.java} was deleted —
     * that is {@link ProjectRepair}'s job, and it regenerates the file with the values the template defines
     * rather than guessing.
     *
     * @return the entry point's new contents when it was rewritten, or {@code null} when nothing changed — so
     *         the caller can refresh the copy the editor holds in memory
     */
    public static String migrate(ProjectConfig config) throws IOException {
        Path settingsFile = fileFor(config.mainSourceFile());
        if (settingsFile == null || Files.exists(settingsFile)) return null;

        Path main = config.mainSourceFile();
        String source = Files.exists(main) ? Files.readString(main) : null;
        if (source == null) return null;

        boolean realInput = ProjectCreator.readRealInput(main);
        write(main, config.packageName(), DEFAULTS.withRealInput(realInput));

        Matcher inline = INLINE_REAL_INPUT.matcher(source);
        String updated;
        if (inline.find()) {
            updated = new StringBuilder(source)
                    .replace(inline.start(), inline.end(), "        BotSettings.apply();\n")
                    .toString();
        } else {
            Matcher m = MAIN_METHOD.matcher(source);
            if (!m.find()) return null;
            updated = new StringBuilder(source)
                    .insert(m.end(), "\n        BotSettings.apply();")
                    .toString();
        }
        // The import goes with the call: BotSettings is in the same package, and a leftover unused import of a
        // type the entry point no longer mentions is a warning the user didn't write. "No longer mentions" is
        // judged with the import line itself removed — it is the one occurrence that must not count.
        String importLine = "import com.botmaker.sdk.api.vision.ClickConfig;\n";
        String withoutImport = updated.replace(importLine, "");
        if (!withoutImport.contains("ClickConfig")) {
            updated = withoutImport;
        }
        Files.writeString(main, updated);
        return updated;
    }
}
