package com.botmaker.studio.project;

import java.nio.file.Path;

/**
 * What a project file <em>is</em>, from the editor's point of view — the single source of truth for which
 * files the user owns and which are scaffolding.
 *
 * <p>Before this existed the rules were duplicated as inline path checks in {@code CodeEditorService.refreshUI}
 * and half-mirrored in {@code FileExplorerManager}'s cell factory, which is how {@code ActivityRegistry.java}
 * ended up read-only in the editor but freely deletable (with no confirmation) from the tree. Anything that
 * needs to know "may the user change this?" asks {@link #of} — do not re-derive it from a path.
 *
 * <p>This is a <b>file</b>-level verdict. "This whole file is the user's, but one method in it is load-bearing"
 * is {@link MethodLock}'s job — see {@code GoHome.run}, which the SDK's {@code Bot.supervise} binds as a
 * {@code Runnable} even though the file around it is {@link #EDITABLE}.
 */
public enum FileRole {

    /** Ordinary user code. Fully editable, edits persist. */
    EDITABLE,

    /**
     * Scaffolding the Studio generates and owns: the game-bot entry point, {@code ActivityRegistry},
     * {@code Activities}, the game loop, and {@code Startup} (generated {@code StartMode}-driven target launch).
     *
     * <p>Locked by default: no menus, no drop targets, no edits. Interactivity is not a gentler contract than a
     * lock — an edit that appears to work, survives until the next reload and then vanishes with no warning is
     * worse than one that was never offered. If it can't be saved, it must not be offered.
     *
     * <p><b>But "the file is generated" does not mean "every method in it is".</b> A
     * {@link MethodLock#SIGNATURE} method inside a generated file keeps an editable body; only its signature
     * and the code around it are locked. (No game-bot scaffold file currently carries such a grant —
     * {@code GameLoop.run} used to, wrongly, before the dispatch loop was recognised as generated wiring — but
     * the rule is the mechanism, not today's file list.) So the rule is <em>this file's locked parts can't be
     * saved</em>, not <em>this file can't be saved</em> — see {@code LockedRegions}, which decides what may be
     * flushed, and {@code LockResolver}, which combines this verdict with {@link MethodLock}'s. Do not
     * reintroduce a whole-file skip.
     *
     * <p>They are not deletable from the explorer — the "Delete File" action is disabled for them, since
     * removing scaffolding breaks the build (Project ▸ Recover Project Files regenerates them).
     */
    GENERATED,

    /** Bundled library source under {@code com/botmaker/library}. Fully locked: no interaction at all. */
    LIBRARY;

    /** True when this file is scaffolding, so edits are locked unless a {@link MethodLock} grants them. */
    public boolean isReadOnly() {
        return this != EDITABLE;
    }

    /** True when blocks default to refusing interaction (menus suppressed) — again, modulo {@link MethodLock}. */
    public boolean suppressesInteraction() {
        return this != EDITABLE;
    }

    /**
     * A short suffix for the editor status line / explorer label, or {@code null} for ordinary files.
     *
     * <p>{@link #GENERATED} does not say "read-only": a generated file can contain a method whose body is
     * entirely the user's (a {@code MethodLock.SIGNATURE} grant), so a blanket claim on the status line could
     * contradict an editable body right there on screen. The per-method truth is told per method, by
     * {@code MethodLock}'s own badge.
     */
    public String badge() {
        return switch (this) {
            case EDITABLE -> null;
            case GENERATED -> "Generated by BotMaker";
            case LIBRARY -> "Library - Read Only";
        };
    }

    /** The file names the game-bot template generates and owns, alongside the entry point. */
    private static final String GAME_LOOP_FILE = "GameLoop.java";
    private static final String STARTUP_FILE = "Startup.java";

    /**
     * Classifies {@code file} for {@code config}, given the project's {@code template}. Never null; unknown
     * files are {@link #EDITABLE}, so a file the Studio doesn't recognise always belongs to the user.
     *
     * <p>{@code template} decides <b>all</b> of it: only the {@link ProjectTemplate#GAME_BOT} template generates
     * any of these files (the entry point is just {@code Bot.supervise(GameLoop::run, GoHome::run, Startup::run)}).
     * An {@link ProjectTemplate#EMPTY} project's {@code main} is the user's only file and must stay editable, and
     * so must a {@code GameLoop.java} the user happened to write themselves — a null {@code template} (legacy
     * project, or a caller that doesn't know) is therefore treated as EMPTY and nothing is scaffolding.
     */
    public static FileRole of(ProjectConfig config, ProjectTemplate template, Path file) {
        if (config == null || file == null) return EDITABLE;

        String normalized = file.toString().replace("\\", "/");
        if (normalized.contains("com/botmaker/library")) return LIBRARY;
        if (template != ProjectTemplate.GAME_BOT) return EDITABLE;

        Path abs = file.toAbsolutePath();
        if (sameFile(abs, config.mainSourceFile())
                || sameFile(abs, config.activitiesSourceFile())
                || sameFile(abs, config.activityRegistrySourceFile())
                || sameFile(abs, config.flowDriverSourceFile())
                || sameFile(abs, gameLoopSourceFile(config))
                || sameFile(abs, startupSourceFile(config))) {
            return GENERATED;
        }
        return EDITABLE;
    }

    /** {@code GameLoop.java}, which sits beside the entry point in the main package. */
    public static Path gameLoopSourceFile(ProjectConfig config) {
        Path mainDir = config.mainSourceFile().getParent();
        return mainDir == null ? null : mainDir.resolve(GAME_LOOP_FILE);
    }

    /**
     * {@code Startup.java}, which sits beside the entry point in the main package. It is generated wiring now —
     * its {@code run(StartMode)} drives the project's configured launch target (skip-if-running on a cold start,
     * force-stop-then-relaunch on a restart) — so it is locked like {@code GameLoop.java} rather than left as a
     * user-editable stub.
     */
    public static Path startupSourceFile(ProjectConfig config) {
        Path mainDir = config.mainSourceFile().getParent();
        return mainDir == null ? null : mainDir.resolve(STARTUP_FILE);
    }

    private static boolean sameFile(Path abs, Path other) {
        return other != null && abs.equals(other.toAbsolutePath());
    }
}
