package com.botmaker.studio.project;

import com.botmaker.studio.project.activity.ActivitiesConfig;
import com.botmaker.studio.project.activity.ActivityDefinition;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Finds and regenerates project files that have gone missing — typically deleted outside the Studio (an
 * {@code rm}, a bad merge, a sync conflict), which nothing else notices: {@code ProjectManager.isValidProject}
 * only checks that {@code src/main/java} and {@code pom.xml} exist, so a project missing {@code GameLoop.java}
 * opens happily and then fails to compile.
 *
 * <p>Generalises the {@code ActivityService.ensureStubs} pattern: <b>only ever creates what is absent, never
 * overwrites what is there.</b> Recovery must not be able to destroy the user's work.
 *
 * <p>Sources come from {@link ProjectCreator#sourcesFor} and {@code ActivityService}'s generators — this class
 * holds no templates of its own. (It briefly held a copy of the empty-project entry point, which promptly
 * drifted from the real one and lost an import, so a "recovered" project didn't compile. Hence the rule.)
 */
public final class ProjectRepair {

    private ProjectRepair() {}

    /** {@code ActivityRegistry.java}, which both the game-bot scaffold and {@code ActivityService} can produce. */
    private static final String REGISTRY_FILE = "ActivityRegistry.java";

    /**
     * A file that should exist but doesn't, plus the source that would restore it — or a {@code null} source for
     * the files only {@code ActivityService} can regenerate (see {@link #needsActivityRegeneration}).
     */
    public record Missing(Path path, String source, String reason) {
        public String fileName() { return path.getFileName().toString(); }
    }

    /**
     * Guesses whether {@code config}'s project is a game-bot project, from its sources: the entry point calls
     * {@code Bot.supervise}, or any of the scaffold files is still present.
     *
     * <p><b>Prefer the persisted template</b> ({@link StudioProjectSettings#template()}, resolved once into
     * {@link ProjectState#getTemplate()} at open). This heuristic is the fallback for projects created before
     * the template was recorded, and it has a real cliff: a game-bot project with <em>every</em> scaffold file
     * deleted and a rewritten main is indistinguishable from an empty one — which is exactly the wrecked
     * project recovery most needs to fix.
     */
    public static boolean looksLikeGameBot(ProjectConfig config) {
        Path mainDir = config.mainSourceFile().getParent();
        if (mainDir == null) return false;

        if (Files.exists(config.mainSourceFile())) {
            try {
                if (Files.readString(config.mainSourceFile()).contains("Bot.supervise")) return true;
            } catch (IOException ignored) {
                // Unreadable main: fall through to the file-presence check.
            }
        }
        for (String name : List.of("GameLoop.java", "GoHome.java", "Startup.java", "ActivityRegistry.java")) {
            if (Files.exists(mainDir.resolve(name))) return true;
        }
        return false;
    }

    /**
     * Everything that is missing and recoverable, in a stable order. Empty when the project is intact.
     *
     * <p>{@code template} says which scaffold the project is supposed to have; a null template falls back to
     * {@link #looksLikeGameBot}. Anything the Studio generates is fair game here — not just the template's
     * source files, but {@code Activities.java}, {@code ActivityRegistry.java} and {@code activities.json},
     * which are generated by {@code ActivityService} and were previously unchecked. The explorer's delete
     * dialog promises Recover can bring them back, so it has to actually be able to.
     */
    public static List<Missing> findMissing(ProjectConfig config, ProjectTemplate template,
                                            ActivitiesConfig activities) {
        List<Missing> missing = new ArrayList<>();
        Path mainDir = config.mainSourceFile().getParent();
        if (mainDir == null) return missing;

        ProjectTemplate resolved = template != null
                ? template
                : (looksLikeGameBot(config) ? ProjectTemplate.GAME_BOT : ProjectTemplate.EMPTY);

        // The registry's scaffold source is an *empty* List.of() — correct only while the project has no
        // activities. Once it has some, only ActivityService can rebuild it, so leave it to the pass below.
        boolean hasActivities = activities != null && !activities.activities().isEmpty();

        String reason = resolved == ProjectTemplate.GAME_BOT ? "game-bot scaffold" : "entry point";
        for (Map.Entry<String, String> e :
                ProjectCreator.sourcesFor(resolved, config.projectName(), config.packageName()).entrySet()) {
            if (hasActivities && REGISTRY_FILE.equals(e.getKey())) continue;
            Path path = mainDir.resolve(e.getKey());
            if (!Files.exists(path)) {
                missing.add(new Missing(path, e.getValue(), reason));
            }
        }

        if (activities != null) {
            // activities.json holds every activity's configured value; losing it silently resets them all to
            // defaults, which no other check would notice. Only expected once there is something to store —
            // a project with no activities has never written one, and that is not a fault.
            //
            // This can only fire for a file deleted while the project is open: activities are read from this
            // very file at open, so if it was already gone the in-memory config is empty and there is nothing
            // left to restore it from. Recovery can't invent values it never saw.
            Path json = config.resourcesRoot().resolve(ActivitiesConfig.FILE_NAME);
            if (!activities.allVariables().isEmpty() && !Files.exists(json)) {
                missing.add(new Missing(json, null, "activity settings"));
            }

            // Activities.java only exists when there is something to put in it — ActivityService deletes it
            // when there are no variables at all, so an absent-and-empty one is correct, not missing.
            if (!activities.allVariables().isEmpty() && !Files.exists(config.activitiesSourceFile())) {
                missing.add(new Missing(config.activitiesSourceFile(), null, "generated activity code"));
            }
            if (hasActivities && !Files.exists(config.activityRegistrySourceFile())) {
                missing.add(new Missing(config.activityRegistrySourceFile(), null, "generated activity code"));
            }

            // Per-activity subclass stubs (the same set ActivityService.ensureStubs would create).
            for (ActivityDefinition a : activities.activities()) {
                Path stub = config.activitiesPackageDir().resolve(a.name() + ".java");
                if (!Files.exists(stub)) {
                    missing.add(new Missing(stub, null, "activity stub"));
                }
            }
        }
        return missing;
    }

    /**
     * Creates every file reported by {@link #findMissing}, and returns what was actually written.
     *
     * <p>Entries with a {@code null} source are activity stubs: they are left to {@code ActivityService}, whose
     * {@code update(...)} regenerates the registry as well — see {@code needsActivityRegeneration}.
     */
    public static List<Path> recover(ProjectConfig config, List<Missing> missing) throws IOException {
        List<Path> written = new ArrayList<>();
        for (Missing m : missing) {
            if (m.source() == null) continue;
            if (Files.exists(m.path())) continue;      // re-check: never clobber
            Files.createDirectories(m.path().getParent());
            Files.writeString(m.path(), m.source());
            written.add(m.path());
        }
        return written;
    }

    /** True when {@code missing} contains activity stubs, which only {@code ActivityService} can regenerate. */
    public static boolean needsActivityRegeneration(List<Missing> missing) {
        return missing.stream().anyMatch(m -> m.source() == null);
    }

    /** Groups {@code missing} by reason, for a readable confirmation dialog. */
    public static Map<String, List<String>> summarise(List<Missing> missing) {
        Map<String, List<String>> byReason = new LinkedHashMap<>();
        for (Missing m : missing) {
            byReason.computeIfAbsent(m.reason(), k -> new ArrayList<>()).add(m.fileName());
        }
        return byReason;
    }
}
