package com.botmaker.studio.services;

import com.botmaker.studio.events.CoreApplicationEvents.ActivitiesChangedEvent;
import com.botmaker.studio.events.EventBus;
import com.botmaker.studio.project.ProjectConfig;
import com.botmaker.studio.project.ProjectState;
import com.botmaker.studio.project.activity.ActivitiesConfig;
import com.botmaker.studio.project.activity.ActivityVariable;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

/**
 * Orchestrates the project's <em>activities</em> — editor-defined global config variables. The editor
 * defines names + types; the user fills values. Persistence is split:
 * <ul>
 *   <li>{@code src/main/resources/activities.json} — the schema + values (read at runtime)</li>
 *   <li>generated {@code Activities.java} — a class of {@code public static final} typed fields loaded
 *       from that JSON in a {@code static} initializer, so blocks can reference {@code Activities.<name>}</li>
 * </ul>
 *
 * All I/O lives here at the service edge. {@link #update} runs off the calling thread and publishes
 * {@link ActivitiesChangedEvent} once state is refreshed.
 */
public final class ActivityService {

    private final ProjectConfig config;
    private final ProjectState state;
    private final EventBus eventBus;

    public ActivityService(ProjectConfig config, ProjectState state, EventBus eventBus) {
        this.config = config;
        this.state = state;
        this.eventBus = eventBus;
    }

    /** The current activities (from project state, loaded at open and refreshed on change). */
    public ActivitiesConfig current() {
        ActivitiesConfig c = state.getActivities();
        return c != null ? c : ActivitiesConfig.empty();
    }

    /** Loads activities from disk into project state (called once at project open). */
    public ActivitiesConfig load() {
        ActivitiesConfig loaded = ActivitiesConfig.read(config.resourcesRoot());
        state.setActivities(loaded);
        return loaded;
    }

    /**
     * Persists {@code newConfig} (writes {@code activities.json} and regenerates {@code Activities.java}),
     * refreshes project state and publishes {@link ActivitiesChangedEvent}. Runs asynchronously; the
     * returned future completes exceptionally if writing fails.
     */
    public CompletableFuture<Void> update(ActivitiesConfig newConfig) {
        return CompletableFuture.runAsync(() -> {
            try {
                newConfig.write(config.resourcesRoot());
                writeGeneratedClass(newConfig);
            } catch (IOException e) {
                throw new RuntimeException("Failed to save activities: " + e.getMessage(), e);
            }
            state.setActivities(newConfig);
            eventBus.publish(new ActivitiesChangedEvent(newConfig));
        });
    }

    /** Writes (or deletes, when empty) the generated {@code Activities.java} sidecar. */
    private void writeGeneratedClass(ActivitiesConfig cfg) throws IOException {
        Path file = config.activitiesSourceFile();
        if (cfg.activities().isEmpty()) {
            Files.deleteIfExists(file);
            return;
        }
        Files.createDirectories(file.getParent());
        Files.writeString(file, generateSource(cfg));
    }

    /** Builds the source of the generated {@code Activities} class. */
    String generateSource(ActivitiesConfig cfg) {
        StringBuilder fields = new StringBuilder();
        StringBuilder inits = new StringBuilder();
        boolean needsTime = false;
        boolean needsDate = false;
        for (ActivityVariable a : cfg.activities()) {
            String nodeExpr = "node(v, \"" + a.name() + "\")";
            if (a.description() != null && !a.description().isBlank()) {
                fields.append("    /** ").append(a.description().replace("*/", "*\\/")).append(" */\n");
            }
            fields.append("    public static final ").append(a.type().javaType())
                    .append(' ').append(a.name()).append(";\n");
            inits.append("        ").append(a.name()).append(" = ")
                    .append(a.type().loadExpression(nodeExpr)).append(";\n");
            needsTime |= a.type() == com.botmaker.studio.project.activity.ActivityType.TIME;
            needsDate |= a.type() == com.botmaker.studio.project.activity.ActivityType.DATE;
        }
        return String.format("""
                package com.%s;

                import com.fasterxml.jackson.databind.JsonNode;
                import com.fasterxml.jackson.databind.ObjectMapper;
                import com.fasterxml.jackson.databind.node.MissingNode;

                import java.io.InputStream;
                import java.util.HashMap;
                import java.util.Map;

                /**
                 * Global activities for this bot. GENERATED by BotMaker Studio — do not edit by hand;
                 * manage via Project &rarr; Manage Activities. Values are loaded at startup from
                 * {@code /activities.json} on the classpath. Missing file / missing key / wrong-type or
                 * unparseable values all fall back to each type's default — a bot never fails to start
                 * because of its activities file.
                 */
                public final class Activities {
                %s
                    static {
                        Map<String, JsonNode> v = new HashMap<>();
                        try (InputStream in = Activities.class.getResourceAsStream("/%s")) {
                            if (in != null) {
                                JsonNode root = new ObjectMapper().readTree(in);
                                for (JsonNode a : root.path("activities")) {
                                    v.put(a.path("name").asText(), a.path("value"));
                                }
                            }
                        } catch (Exception e) {
                            // Degrade gracefully: keep the defaults rather than crash the bot at startup.
                            System.err.println("Activities: could not load /%s (" + e.getMessage()
                                    + "); using defaults.");
                        }
                %s    }

                    private static JsonNode node(Map<String, JsonNode> v, String name) {
                        return v.getOrDefault(name, MissingNode.getInstance());
                    }
                %s%s
                    private Activities() {}
                }
                """, config.packageName(), fields.toString().stripTrailing(),
                ActivitiesConfig.FILE_NAME, ActivitiesConfig.FILE_NAME, inits,
                needsTime ? TIME_HELPER : "", needsDate ? DATE_HELPER : "");
    }

    /** Generated helper: parse a {@code LocalTime}, defaulting on a missing/invalid/wrong-type node. */
    private static final String TIME_HELPER = """

            private static java.time.LocalTime parseTime(JsonNode n) {
                    try {
                        return java.time.LocalTime.parse(n.asText("00:00"));
                    } catch (Exception e) {
                        return java.time.LocalTime.MIDNIGHT;
                    }
                }
        """;

    /** Generated helper: parse a {@code LocalDate}, defaulting on a missing/invalid/wrong-type node. */
    private static final String DATE_HELPER = """

            private static java.time.LocalDate parseDate(JsonNode n) {
                    try {
                        return java.time.LocalDate.parse(n.asText("2000-01-01"));
                    } catch (Exception e) {
                        return java.time.LocalDate.of(2000, 1, 1);
                    }
                }
        """;
}
