package com.botmaker.studio.services;

import com.botmaker.studio.project.settings.JavaLiterals;
import com.botmaker.studio.project.settings.RawSetting;
import com.botmaker.studio.project.settings.Setting;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Renders the two generated files that hold a project's settings: the {@code @Setting} annotation, and the
 * {@code Settings} class whose fields <em>are</em> the values.
 *
 * <p>Pure — a package name and a list of {@link Setting}s in, two source strings out. It writes nothing and
 * reads nothing; {@link ActivityService} owns the I/O, as everything at the service edge does.
 *
 * <p><b>Two properties of the emitted shape are load-bearing and must not be tidied away.</b>
 *
 * <p>First, <b>every field is a blank final assigned in a static initializer</b>, never
 * {@code public static final int RETRIES = 3;}. An inline constant initializer would make the field a JLS
 * §4.12.4 <em>constant variable</em>, which javac folds into every use site — and
 * {@code while (Settings.SOME_FLAG) { … }} with a constant-{@code false} flag is then an
 * {@code unreachable statement} <em>compile error</em>. A bot would stop compiling because its user unticked a
 * box in the Runner. A blank final assigned in a static block is not a constant variable, so none of that
 * applies. The old JSON-reading generator had this property by accident; this one has it on purpose.
 *
 * <p>Second, <b>the canonical value lives in {@code @Setting(value = …)} as text, and the initializer is pure
 * output.</b> Studio writes the static block and never reads it back: recovering a value from
 * {@code java.time.Duration.ofMillis(90000L)} would mean parsing arbitrary Java expressions, where recovering
 * it from {@code value = "90s"} means reading one string literal. It is the same bijection discipline
 * {@link com.botmaker.studio.project.TemplateConstants} documents for template names — the generated file is
 * the store, so what Studio wrote has to be exactly what Studio can read.
 *
 * <p>Every type name and every literal is <b>fully qualified</b>, which is why neither generated file has an
 * import block: the cheapest way to guarantee a generated file never needs an import somebody forgot.
 */
public final class SettingsClassWriter {

    /** The generated class holding the values, in the project's base package beside {@code Templates}. */
    public static final String SETTINGS_CLASS = "Settings";

    /** The generated annotation carrying what Java's type system cannot say about a field. */
    public static final String ANNOTATION_CLASS = "Setting";

    private SettingsClassWriter() {}

    /**
     * The whole {@code Setting.java} source — fixed content, written once per project and regenerated only so
     * a project repaired after losing it comes back identical.
     *
     * <p>It lives in the bot rather than in the SDK on purpose: a bot pins the SDK version <em>it</em> chose,
     * which may be older than Studio, so an annotation shipped in the SDK would put an ordered SDK release on
     * the critical path of every settings change. Generated into the bot, it is always exactly the version
     * that wrote the file next to it.
     */
    public static String annotationSource(String packageName) {
        return String.format("""
                package com.%s;

                /**
                 * What BotMaker Studio knows about a field of {@link %s} that Java's type system cannot say:
                 * which group it is filed under, whether the bot's user is offered it, the choices it may take,
                 * and — in {@link #value()} — the canonical text of the value the field is assigned.
                 *
                 * <p>GENERATED by BotMaker Studio — do not edit by hand. Nothing in the bot reads it at run
                 * time; it exists so Studio can read its own settings back out of the file it wrote.
                 */
                @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.RUNTIME)
                @java.lang.annotation.Target(java.lang.annotation.ElementType.FIELD)
                public @interface %s {

                    /** The kind of value: TEXT, INT, DURATION, CHOICE, … */
                    String type();

                    /** The group this is listed under; empty means General. */
                    String tag() default "";

                    /** A human-readable name shown instead of the field name. */
                    String label() default "";

                    /** Whether the person running the bot is offered this in the Runner window. */
                    boolean shared() default false;

                    /** The canonical text of the value — what Studio reads back. Single-valued types only. */
                    String value() default "";

                    /** The canonical text of each value, for a multiple-choice setting. */
                    String[] values() default {};

                    /** The choices on offer, for a single- or multiple-choice setting. */
                    String[] options() default {};

                    /** The lowest value allowed, for a bounded number. */
                    String min() default "";

                    /** The highest value allowed, for a bounded number. */
                    String max() default "";

                    /** How far one nudge of the widget moves the value, for a bounded number. */
                    String step() default "";
                }
                """, packageName, SETTINGS_CLASS, ANNOTATION_CLASS);
    }

    /**
     * The whole {@code Settings.java} source for {@code settings}, in the given package.
     *
     * <p>Written even with no settings at all, for the reason the generated {@code Activities} and
     * {@code Templates} classes are: a hand-written {@code import com.<pkg>.Settings;} has to keep compiling
     * after the last setting is deleted. An empty class costs nothing and cannot break a build.
     *
     * <p>Fields are grouped by {@link Setting#tagOrGeneral() tag}, tags in the order they first appear in
     * {@code settings} and the settings within one in the order they were given — so the file reads in the
     * order the dialog that produced it shows, and a diff of two saves is the edit that was made rather than a
     * reshuffle. A setting whose name is not a legal Java identifier, or that repeats a name already emitted,
     * is skipped: either one is a compile error in a file nobody can fix by hand.
     */
    public static String settingsSource(String packageName, List<Setting> settings) {
        return settingsSource(packageName, settings, List.of());
    }

    /**
     * As {@link #settingsSource(String, List)}, re-emitting {@code unknown} verbatim after the settings.
     *
     * <p>Those are the fields {@link SettingsReader} could not understand — a {@code type} written by a newer
     * Studio. They are written back as the exact source they were read from, because the alternative is that
     * opening a project in an older Studio and saving it deletes settings that Studio simply never learned
     * about. They are grouped under one heading of their own rather than filed by tag: this build cannot read
     * their tag, and guessing one would move a field for no reason a diff could explain.
     */
    public static String settingsSource(String packageName, List<Setting> settings, List<RawSetting> unknown) {
        Map<String, List<Setting>> byTag = groupByTag(settings);

        StringBuilder fields = new StringBuilder();
        StringBuilder inits = new StringBuilder();
        Set<String> emitted = new LinkedHashSet<>();
        for (Map.Entry<String, List<Setting>> group : byTag.entrySet()) {
            fields.append("\n    // ").append(group.getKey()).append('\n');
            for (Setting setting : group.getValue()) {
                Setting normalized = setting.normalized();
                emitted.add(normalized.name());
                fields.append("\n    ").append(annotationFor(normalized)).append('\n');
                fields.append("    public static final ").append(normalized.type().javaType())
                        .append(' ').append(normalized.name()).append(";\n");
                inits.append("        ").append(normalized.name()).append(" = ")
                        .append(normalized.literal()).append(";\n");
            }
        }

        boolean firstUnknown = true;
        for (RawSetting raw : unknown == null ? List.<RawSetting>of() : unknown) {
            // A live setting that has taken the name wins: two fields called the same thing is a file that
            // does not compile, and the one this build understands is the one it can still fix.
            if (raw == null || !isIdentifier(raw.name()) || !emitted.add(raw.name())) continue;
            if (firstUnknown) {
                fields.append("\n    // Written by a newer version of BotMaker Studio\n");
                firstUnknown = false;
            }
            fields.append("\n    ").append(raw.annotation()).append('\n');
            fields.append("    public static final ").append(raw.javaType())
                    .append(' ').append(raw.name()).append(";\n");
            inits.append("        ").append(raw.name()).append(" = ").append(raw.initializer()).append(";\n");
        }

        return String.format("""
                package com.%s;

                /**
                 * Every setting of this bot, with its value. GENERATED by BotMaker Studio — do not edit by
                 * hand; manage via Project &rarr; Settings. Studio rewrites this file whole on every change,
                 * and reads its own values back out of the {@link %s} annotations, so an edit made here is
                 * lost at the next save.
                 *
                 * <p>Read one wherever the bot needs it: {@code Settings.RETRIES}. Each field is assigned in
                 * the static initializer below rather than in its declaration — that is deliberate, and
                 * changing it would make every field a compile-time constant that javac folds into its use
                 * sites, so a flag turned off in the Runner would turn {@code while (Settings.FLAG)} into an
                 * unreachable-statement compile error.
                 */
                public final class %s {
                %s

                    static {
                %s    }

                    private %s() {}
                }
                """, packageName, ANNOTATION_CLASS, SETTINGS_CLASS,
                fields.toString().stripTrailing(), inits, SETTINGS_CLASS);
    }

    /** The settings that can actually be emitted, grouped by tag in first-appearance order. */
    private static Map<String, List<Setting>> groupByTag(List<Setting> settings) {
        Map<String, List<Setting>> byTag = new LinkedHashMap<>();
        Set<String> emitted = new LinkedHashSet<>();
        for (Setting setting : settings == null ? List.<Setting>of() : settings) {
            if (setting == null) continue;
            String name = setting.name();
            if (!isIdentifier(name) || !emitted.add(name)) continue;
            byTag.computeIfAbsent(setting.tagOrGeneral(), t -> new ArrayList<>()).add(setting);
        }
        return byTag;
    }

    /** The {@code @Setting(…)} line for one setting: everything it knows, minus everything at its default. */
    static String annotationFor(Setting setting) {
        List<String> elements = new ArrayList<>();
        elements.add("type = " + JavaLiterals.string(setting.type().name()));
        if (!setting.tag().isBlank()) elements.add("tag = " + JavaLiterals.string(setting.tag()));
        if (!setting.label().isBlank()) elements.add("label = " + JavaLiterals.string(setting.label()));
        if (setting.isShared()) elements.add("shared = true");
        if (setting.type().isMultiValued()) {
            elements.add("values = " + array(setting.value()));
        } else {
            elements.add("value = " + JavaLiterals.string(setting.singleValue()));
        }
        // The declared choices, not the effective ones: KEY and MOUSE_BUTTON take theirs from the SDK enum, and
        // writing that list out would freeze a copy of it into every project that uses one.
        if (setting.type().hasOptions() && !setting.options().isEmpty()) {
            elements.add("options = " + array(setting.options()));
        }
        Setting.Bounds bounds = setting.bounds();
        if (bounds.min() != null) elements.add("min = " + JavaLiterals.string(bounds.min()));
        if (bounds.max() != null) elements.add("max = " + JavaLiterals.string(bounds.max()));
        if (bounds.step() != null) elements.add("step = " + JavaLiterals.string(bounds.step()));
        return "@" + ANNOTATION_CLASS + "(" + String.join(", ", elements) + ")";
    }

    /** A {@code {"a", "b"}} array initializer — {@code {}} for nothing, which is the annotation's default. */
    private static String array(List<String> values) {
        return "{" + String.join(", ", values.stream().map(JavaLiterals::string).toList()) + "}";
    }

    /** Whether {@code name} can be a field name at all. Defensive: the model refuses to make one that can't. */
    private static boolean isIdentifier(String name) {
        if (name == null || name.isBlank()) return false;
        if (!Character.isJavaIdentifierStart(name.charAt(0))) return false;
        for (int i = 1; i < name.length(); i++) {
            if (!Character.isJavaIdentifierPart(name.charAt(i))) return false;
        }
        return true;
    }
}
