package com.botmaker.studio.sharing;

/**
 * Static configuration for the federated bot-sharing gallery.
 *
 * <p>Two values are maintainer-owned and must be filled in before publishing / the gallery work
 * end-to-end (see the project plan):
 * <ul>
 *   <li>{@link #OAUTH_CLIENT_ID} — register a GitHub OAuth App with device flow enabled and paste its
 *       (public) client id here. While blank, publishing degrades gracefully ("publishing not configured").</li>
 *   <li>{@link #INDEX_OWNER}/{@link #INDEX_REPO} — the curated index repo holding {@code index.json}. While
 *       it doesn't exist, {@link GitHubGallery#browse()} simply returns an empty catalog.</li>
 * </ul>
 * Browsing / installing public bots needs no GitHub account; only publishing does.
 */
public final class GitHubConfig {

    private GitHubConfig() {}

    public static final String OAUTH_CLIENT_ID = "Ov23lizugeHUiWl7WZhQ";

    public static final String INDEX_OWNER = "LiQiyeDev";
    public static final String INDEX_REPO = "botmaker-gallery";

    /** The Studio's own repo, whose GitHub Releases host the app installers (used by the in-app updater). */
    public static final String STUDIO_OWNER = "LiQiyeDev";
    public static final String STUDIO_REPO = "BotMaker-Studio";

    /** Umbrella repo that receives in-app bug reports (Help ▸ Report Issue…). */
    public static final String ISSUE_OWNER = "LiQiyeDev";
    public static final String ISSUE_REPO = "botmaker";
    public static final String INDEX_BRANCH = "main";

    /**
     * The generated catalog, read by {@link GitHubGallery#browse()}.
     *
     * <p><b>Read only.</b> Studio used to publish by rewriting this whole array, which made every concurrent
     * submission a merge conflict and every delisting a whole-file diff. The gallery's own CI generates it
     * from {@link #ENTRIES_DIR} now, and refuses a pull request that edits it. The path is a compatibility
     * promise in the other direction — a Studio already in the wild has this URL compiled into it — so it
     * must not move.
     */
    public static final String INDEX_PATH = "index.json";

    /** Where one bot's entry lives, and what {@link BotPublisher} writes: {@code bots/<owner>-<repo>.json}. */
    public static final String ENTRIES_DIR = "bots";

    /**
     * The plugin index — the gallery's sibling, read by {@link PluginRegistry}.
     *
     * <p>Studio only ever <em>reads</em> it: a plugin is submitted with {@code botmaker publish} from the
     * CLI, whose validator is the same code the registry's CI runs. There is deliberately no publish path
     * here, because the checks that decide a submission need the plugin's build, not a bot's editor.
     */
    public static final String REGISTRY_OWNER = "LiQiyeDev";
    public static final String REGISTRY_REPO = "botmaker-plugin-registry";

    /** Discovery topic also applied to published repos (secondary signal; the index repo is authoritative). */
    public static final String TOPIC = "botmaker-bot";

    public static final String API_BASE = "https://api.github.com";
    public static final String DEVICE_CODE_URL = "https://github.com/login/device/code";
    public static final String ACCESS_TOKEN_URL = "https://github.com/login/oauth/access_token";
    /**
     * Full {@code repo} rather than {@code public_repo}: the VCS panel's Push button creates and pushes to a
     * <em>private</em> backup repo, which {@code public_repo} cannot do. Tokens issued before this change keep
     * their narrower scope, so the private-repo calls translate the resulting 403/404 into a "sign out and back
     * in" hint rather than a raw API error.
     */
    public static final String SCOPE = "repo";

    /**
     * The path of one bot's entry file, {@code bots/<owner>-<repo>.json}.
     *
     * <p>The filename is the bot's identity, which is what makes two submissions two files that cannot
     * conflict — and makes a delisting a deletion rather than a rewrite.
     */
    public static String entryPath(String owner, String repo) {
        return ENTRIES_DIR + "/" + owner + "-" + repo + ".json";
    }

    /** Raw (CDN) URL of the curated catalog — no API rate limit, no auth. */
    public static String indexRawUrl() {
        return "https://raw.githubusercontent.com/"
                + INDEX_OWNER + "/" + INDEX_REPO + "/" + INDEX_BRANCH + "/" + INDEX_PATH;
    }

    /** Raw (CDN) URL of the plugin index — generated by the registry's CI, read here and never written. */
    public static String registryIndexRawUrl() {
        return "https://raw.githubusercontent.com/"
                + REGISTRY_OWNER + "/" + REGISTRY_REPO + "/" + INDEX_BRANCH + "/" + INDEX_PATH;
    }

    /**
     * Release-archive endpoint for a tag. Deliberately the API's {@code zipball} rather than a direct
     * {@code codeload.github.com} URL: the API form honours an {@code Authorization} header (so a private or
     * rate-limited repo still installs) and answers a 302 to a signed codeload URL that needs no auth of its
     * own — the client follows it.
     */
    public static String archiveUrl(String owner, String repo, String tag) {
        return API_BASE + "/repos/" + owner + "/" + repo + "/zipball/refs/tags/" + tag;
    }

    /** REST endpoint for creating an issue on the umbrella repo (used with an authenticated token). */
    public static String issuesApiUrl() {
        return API_BASE + "/repos/" + ISSUE_OWNER + "/" + ISSUE_REPO + "/issues";
    }

    /** Browser URL of the umbrella repo's "New Issue" page (no auth handled by the app; the browser session is). */
    public static String newIssueBrowserUrl() {
        return "https://github.com/" + ISSUE_OWNER + "/" + ISSUE_REPO + "/issues/new";
    }

    public static boolean isPublishingConfigured() {
        return !OAUTH_CLIENT_ID.isBlank();
    }

    public static boolean isGalleryConfigured() {
        return !INDEX_OWNER.isBlank() && !INDEX_REPO.isBlank();
    }

    public static boolean isRegistryConfigured() {
        return !REGISTRY_OWNER.isBlank() && !REGISTRY_REPO.isBlank();
    }
}
